---
- name: Create frontend local config directory
  file: path="{{ directory }}/app/config/local" state=directory

- name: check value for secure, remove later
  debug: var={{ secure }}

- name: Register frontend template check
  stat: path="{{ directory }}/app/config/local/{{ item | basename | regex_replace('\\.j2', '.php') }}"
  register: exists
  with_fileglob:
        - templates/config/*

- name: Set config for frontend
  template: src="{{ item.item }}" dest="{{ directory }}/app/config/local/{{ item.item | basename | regex_replace('\.j2', '.php') }}" mode=0644
  with_items: exists.results

- name: Set oauth2 package config for frontend
  template: src="templates/config/packages/oauth2.j2" dest="{{ directory }}/app/config/packages/gousto/oauth2/config.php" mode=0644
