---
- name: Ensure role defaults are used for this role
  include_vars: defaults/main.yml

- name: Symlink src to directory
  file: src=/var/www/gousto2frontend/src dest="{{ directory }}" state=link
  when: "{{ environment_name == 'dev' }}"

- name: Copy cfn mappings to conf folder
  copy: src=vars/20_cfn_mapping.yml dest=/mnt/playbooks/conf/20_cfn_mapping.yml mode=755

# this should be moved to platform and be generic but take presedence over the cfn mappings
- name: Map variables
  include_vars: "{{ item }}"
  with_fileglob:
    - /mnt/playbooks/conf/*.yml
  when: "{{ environment_name != 'dev' }}"

- include: config.yml

- name: Set relaxed permissions on storage folder
  file: path="{{ directory }}/app/storage" state=directory recurse=yes mode=0777 owner=www-data group=www-data

- name: Add frontend apache config
  template: src="templates/apache2_frontend.j2" dest="{{ '/etc/apache2/sites-available/25-' + domain + '.conf' }}" owner=root mode=0600
  notify: restart apache2

- name: Enable apache2 core site
  command: "a2ensite {{ '25-' + domain }}"
  notify: restart apache2

- include: awslogs.yml
  when: "{{ environment_name != 'dev' }}"

- include: build.yml
  when: "{{ environment_name == 'dev' }}"

- include: nodeserver.yml

- include: healthcheck.yml
