declare module 'goustouicomponents' {
  import * as GoustoUIComponents from '../../../libs/goustouicomponents/src/main'

  export const Alert: typeof GoustoUIComponents.Alert
  export const Breadcrumbs: typeof GoustoUIComponents.Breadcrumbs
  export const Button: typeof GoustoUIComponents.Button
  export const BottomFixedContent: typeof GoustoUIComponents.BottomFixedContent
  export const Card: typeof GoustoUIComponents.Card
  export const CloseIcon: typeof GoustoUIComponents.CloseIcon
  export const CollectionsNavigation: typeof GoustoUIComponents.CollectionsNavigation
  export const CollectionsNavigationItem: typeof GoustoUIComponents.CollectionsNavigationItem
  export const Column: typeof GoustoUIComponents.Column
  export const CommunicationPanel: typeof GoustoUIComponents.CommunicationPanel
  export const Control: typeof GoustoUIComponents.Control
  export const CookieBanner: typeof GoustoUIComponents.CookieBanner
  export const CookingTime: typeof GoustoUIComponents.CookingTime
  export const CTA: typeof GoustoUIComponents.CTA
  export const CTABack: typeof GoustoUIComponents.CTABack
  export const CTATiles: typeof GoustoUIComponents.CTATiles
  export const CTATilesItem: typeof GoustoUIComponents.CTATilesItem
  export const Cuisine: typeof GoustoUIComponents.Cuisine
  export const LegacyDropdown: typeof GoustoUIComponents.LegacyDropdown
  export const ExtraInfo: typeof GoustoUIComponents.ExtraInfo
  export const ExtraInfoMain: typeof GoustoUIComponents.ExtraInfoMain
  export const ExtraInfoSecondary: typeof GoustoUIComponents.ExtraInfoSecondary
  export const ExpandableSection: typeof GoustoUIComponents.ExpandableSection
  export const ExpandingText: typeof GoustoUIComponents.ExpandingText
  export const FloatCard: typeof GoustoUIComponents.FloatCard
  export const Footer: typeof GoustoUIComponents.Footer
  export const Grid: typeof GoustoUIComponents.Grid
  export const Header: typeof GoustoUIComponents.Header
  export const Heading: typeof GoustoUIComponents.Heading
  export const InfoTip: typeof GoustoUIComponents.InfoTip
  export const InputCheck: typeof GoustoUIComponents.InputCheck
  export const InputField: typeof GoustoUIComponents.InputField
  export const InputRadio: typeof GoustoUIComponents.InputRadio
  export const Item: typeof GoustoUIComponents.Item
  export const ItemExpandable: typeof GoustoUIComponents.ItemExpandable
  export const Layout2Cells: typeof GoustoUIComponents.Layout2Cells
  export const LayoutContentWrapper: typeof GoustoUIComponents.LayoutContentWrapper
  export const LayoutPageWrapper: typeof GoustoUIComponents.LayoutPageWrapper
  export const List: typeof GoustoUIComponents.List
  export const Loader: typeof GoustoUIComponents.Loader
  export const MetaInfo: typeof GoustoUIComponents.MetaInfo
  export const Modal: typeof GoustoUIComponents.Modal
  export const ModalBody: typeof GoustoUIComponents.ModalBody
  export const ModalHeader: typeof GoustoUIComponents.ModalHeader
  export const NarrowCard: typeof GoustoUIComponents.NarrowCard
  export const OrderDetails: typeof GoustoUIComponents.OrderDetails
  export const OrderState: typeof GoustoUIComponents.OrderState
  export const Pill: typeof GoustoUIComponents.Pill
  export const ProgressBar: typeof GoustoUIComponents.ProgressBar
  export const RadioGroup: typeof GoustoUIComponents.RadioGroup
  export const Rating: typeof GoustoUIComponents.Rating
  export const RecipeCard: typeof GoustoUIComponents.RecipeCard
  export const RecipesImagery: typeof GoustoUIComponents.RecipesImagery
  export const ScrollCarousel: typeof GoustoUIComponents.ScrollCarousel
  export const ScrollCarouselBody: typeof GoustoUIComponents.ScrollCarouselBody
  export const Segment: typeof GoustoUIComponents.Segment
  export const Spinner: typeof GoustoUIComponents.Spinner
  export const StepIndicator: typeof GoustoUIComponents.StepIndicator
  export const Tooltip: typeof GoustoUIComponents.Tooltip
  export const Stepper: typeof GoustoUIComponents.Stepper
  export const TimeIndicator: typeof GoustoUIComponents.TimeIndicator
  export const VerticalStages: typeof GoustoUIComponents.VerticalStages
  export const VerticalStagesItem: typeof GoustoUIComponents.VerticalStagesItem
  export const Dropdown: typeof GoustoUIComponents.Dropdown
  export const NavDropdown: typeof GoustoUIComponents.NavDropdown
}
