enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/":
    npmAlwaysAuth: true
    npmAuthToken: eyJ2ZXIiOjEsImlzdSI6MTY0MzAyNjc2MywiZW5jIjoiQTEyOEdDTSIsInRhZyI6IlZ4NGlQd2dYdlV4SmowUnNtbGRzU2ciLCJleHAiOjE2NDMwNjk5NjMsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiZGI2Mm1zNXhycFQwWGtUbCJ9.Z8tbP4JHlNUCk9c8FRJlNQ.uvxhMXCizM7leb7s.uaJPh5NTvsJjEkcruyfLTDu0k8Ikc3xtvbXow6Z9YJgnUfGaLuCUOkgkmyEOIoVdG3-UZIJ5jHMH8qjnkStzI22w7Uzum6VnfWtbVFJquSundmgJe3I3YjJ03MnoBHBYiOKg6t_DKKJFBVgqpWg2FBgmGy8NSyP1MbQbpffIWbbq15UL7vmUP6Eq_rEb5psOYXmD27LyqJWfLyOHtpMnZZ4huTlk-psdjGKAUEdn_bHTidGuVQ3VPPMN1zI4A4z4KzdCChCqqoYD23u5zpm4MnWsU80a_hm-LQOBIgyKkebpNs4aHjqpJFWiMaVT2VomfR3qt_A8oShBRavnZN-r1OwIQBShbmuScZq85_tbG8HhFSwhcGz93V9wYgpdDRXZsafPISZoffObNUoYJPUHaRY7POx4R0_czwVKyFC7Chgj85fwHw2RgcdgCvgGPiib46f64lJEefgDZVHKMkPZH1Mt175-AUCrr3XJWvawzOmC1_GtEwZYIZIbV_cwHZwtvasru5Xn-XPzeASd6sTbAKTSXyha-x6c3M6ZBMBxU7XkU9qWgpb6omvSygq1aSoYkNVB81IimZ8MwQOWDTgWx6ef3H-J2I8AxfbLD2q1UbPCunRVaKXK8F9eFpynECuqPPfthfzHd38wGZfPODi1sdOLaUAYk2-kg3XNaUs5eViZGIygdOmug24MDNDhUKzXOC0dv8Qe-T6UXduKZ7xL-kplq32Aci8BceVUIBut3SNAFepolzElijfWBHzcKCU8Ldtg7uk3vZOsiDxRWHsSoGCPklowA9UYVtLsibQzNR0ysBpToua-hrb2gHOiooSXbzybopk5DEAFgbVeuFSpaD4X-6uBmunC-K0uT6i9glRKSjCmFYztwfmSC0pCgW2zT-uLNI3UM_kIrBXHW1FqjsQ.n9hZXWaq53NY-Vvk9ssYaw

npmRegistryServer: "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - .yarn/plugins/gousto/bower-install.js

yarnPath: .yarn/releases/yarn-3.1.1.cjs
