# Has no benefit on OSX: https://github.com/yarnpkg/berry/issues/954#issuecomment-586569711
enableGlobalCache: false

# Continue with node_modules until we have opportunity to test pnp
nodeLinker: node-modules

# Compare tasks should look at /develop
changesetBaseRefs:
  - develop

# Hoisting is disabled
# If we change this, we'll need to change how the webclient webpack config resolves modules
nmHoistingLimits: workspaces

# Avoid workspace packages self-referencing in node_modules
nmSelfReferences: false

# Install the following plugins
# - workspace-tools for workspace commands
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - .yarn/plugins/gousto/bower-install.js
  - .yarn/plugins/gousto/monorepo-build.js

# Our Yarn version management strategy is to keep cjs file in repo; this can be sunset once Node Corepack is default
yarnPath: .yarn/releases/yarn-3.1.1.cjs

# Code artifact registry details
npmScopes:
  gousto-internal:
    npmRegistryServer: "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/"
    npmAlwaysAuth: true
    npmAuthToken: ${CODEARTIFACT_AUTH_TOKEN:-}

npmRegistryServer: https://registry.yarnpkg.com
