enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/":
    npmAlwaysAuth: true
    npmAuthToken: eyJ2ZXIiOjEsImlzdSI6MTY0MzEzMDE5OCwiZW5jIjoiQTEyOEdDTSIsInRhZyI6IjhPdTlWOVJZendteWk2UktFaUtZdnciLCJleHAiOjE2NDMxNzMzOTgsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiTVAybHdGQ25KTUhLN21TbyJ9.LwEfWZmbip82xjYHF9rK-Q.dl_m_YBj4Hzg5lCA.UVmNuCSLQWoGjct37ayZeYpFX-mZDUfVndke6SXhv5Z3qq12tGn811tRIEyqqiD7jfFZkMu-07GIM1YCuQ5IYmF7rnvjsO5ulMs2wyrWfN6KaMHKtRqOoUwo_fPw2ePSEbNu2Pi8KvL8npbpQG8EiNoWT0f6rgtOEUY33qtm0q3RrIGl7Kv45fZ9d1fG0ihta97uP8Jz2YfSqz4aOPdqzVfLe8KatlK7wMPTfSKNsXZeUHcNdj6r4m1FH93BgNlFnpy60QrS0Qm_LkqS7Fl_QD1I5TFIJs9TH742DOt1sKRy7yfCt1T2PrTtjhFUxE0UDe2AFqI0WlPWTdJdKO-83NpCrsdxx7qyj4smEI2Y8wgrTVct_AYbRIXHsPv7Nr5YUBXsBIuRgFAMYDfX35BZSqaH_OBPTmZGGAlYnpqxH-ofn4Al_xvz0eTm7x1EIEZG8SNh39wQjLdQ4mPhpLD_mPehqF__FjKjYFqpJSz8A9bA8Rj1SmTFLxsJnE25uJmRCEMibXMdOCtQkoIzlUoqeNkUmBQGPdWae7SzO56_2aQ7-QFX-bDN7OtefCHtM61OA2F3iUx3otLHR25NeVCqL4GRwBGBl3m8UiuGSejZZuu9iUJsvtwlnHXhcYY9FUk2j17plf6KtVr4p8R5EcbwrIdspj3ScjK-9NNbTjHyex0sdregc9zucdS9M1FpOEQQD8lpjCT1FiXUTt8DH2Dhkn6yppR_G-62Hw6MR20Ns9z9c-2Gh0_NPyiNhiLK6TSrf0dCVqAzPy4LOMqExAr4YWy70O-T1g4b_kD7UiJbX12gvWlWCmlQgPkwdWXok7QEvWRIZ6gv5Rwszfoe5zoCEBaJluPGkwNbhNN3tApOSRbtgwZFUhVwn2g5sOpZaFERTEXaTVLBA4j94sITMQU2RbHyZjbt7YkqbPhiRpqHn2_bzf1n7upbaxy9bZPN1mLSSP94EHU3s_VFwmGy-MtTW0EiDaOTS3Wu3oO95UAyoV-l_IzergDw0YgpbvcXp5kIyY0snhW38EZaF7eoEQTBDztT7uCYcK2QwCNLJNkmfhks_JsasMpVRetxVdRUPntbvBd-xjRlHwxvo1qexy3A-FgWg_1tB7r7ToRmNn_MaMkQvy9i5L7OYmIvfMvQCd1yyzz_rsCBzpDy4bwFoqxFEqWqDfpJjitEhoDcnagdPL_vcfRQMnApWrFnRUf9h12fIaZSjC9wsZ6qY-f2zzLqecrhzxg46_33gAkl1w_x4Qmh-Sf9uiAwWHumxdjX5jBR-vHbtaQHug2KnMwX9SgCBk5Xj8x88QXbsvPm3YyVzQqLKIADiF4.AV5z5_4WGE2_DL-pwfVQMA

npmRegistryServer: "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - .yarn/plugins/gousto/bower-install.js

yarnPath: .yarn/releases/yarn-3.1.1.cjs
