---
serviceName: webclient
region: eu-west-1
exposure: public
dns: webclient
owner: squad-radishes
rootVolumeSize: 16

alb:
  ec2:
    type: public
    rules:
      - priority: 93
        conditions:
          - field: host-header
            value: "[environment]-webclient.[cloudformation_output_domain]"

  ecs:
    - type: public
      rules:
        - priority: 92
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"

messages:
 publish:
 consume:

alarms:
  cpuAmber: 61
  cpuRed: 80
  elbLatencyAmber: 0.8
  elbLatencyRed: 1.2

logs:
  - name: accessLogGroup
  - name: errorLogGroup
  - name: pm2Log
  - name: apiTimeLog

ecs_log_filters:
  - name: applicationlog
    filters:
      - name: AuthServiceTimeoutCount
        pattern: '''{$.message = "auth/login catch {\"code\":500,\"errors\":[],\"message\":\"Timeout\",\"status\":500}"}'''
        alarm:
          description: Alarm to indicate that login requests to auth service are timing out.
          owner: squad-haricots
          level: critical

scaling:
  ecsCpuTargetTrackingScalingPolicyPercentage: 50
  ecsMemoryTargetTrackingScalingPolicyPercentage: 20

healthCheck:
  target : 'HTTP:80/ping'
  healthyThreshold: 2
  unhealthyThreshold: 10
  interval: 5
  timeout: 4
  gracePeriod: 1080

environments:
  - name: staging
    instanceType: t2.small
    minInstanceSize: 0
    maxInstanceSize: 1
    desiredInstanceSize: 0
    ecsDesiredTaskCount: 1
    ecsMaxTaskCount: 2
    ecsMemory: 1024
    ecsCpu: 512

    deployment:
      style: immutable
      minInstancesInService: 0
      maxBatchSize: 1

  - name: env-default
    instanceType: t2.small
    minInstanceSize: 0
    maxInstanceSize: 0
    desiredInstanceSize: 0
    ecsDesiredTaskCount: 1
    ecsMemory: 512
    ecsCpu: 256

    deployment:
      style: inline

  - name: production
    instanceType: t2.medium
    minInstanceSize: 0
    maxInstanceSize: 8
    desiredInstanceSize: 0
    availability: alwaysOn
    ecsDesiredTaskCount: 8
    ecsMaxTaskCount: 16
    ecsMemory: 2048
    ecsCpu: 1024

    deployment:
      style: immutable
      minInstancesInService: 0
      maxBatchSize: 1
