---
serviceName: webclient
exposure: public
dns: webclient
owner: squad-radishes

ec2: false
ecs:
  alb:
    - type: public
      rules:
        - priority: 91
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"

  healthCheck:
    target : 'HTTP:80/ping'
    healthyThreshold: 2
    unhealthyThreshold: 10
    interval: 5
    timeout: 4

  containers:
    webclient:
      port: 80
      logName: application
      environment:
        ENVIRONMENT: '{{ ENVIRONMENT }}'
      configuration:
        datadog_api_key:
          type: secret
          description: API key for datadog agent sidecar
        API_TOKEN:
          type: secret
          description: API token for server request header
        AUTH_CLIENT_ID:
          type: secret
          description: Auth client ID for auth service
        AUTH_CLIENT_SECRET:
          type: secret
          description: Auth client secret for auth service
        RECAPTCHA_RAF_PVTK:
          type: secret
          description: Recaptcha PRIVATE key for RAF
        RECAPTCHA_PVTK:
          type: secret
          description: Private key for login Recaptcha

  taskRolePolicies:
    - effect: Allow
      actions:
        - s3:GetObject
        - s3:GetObjectVersion
      resources:
        - arn:aws:s3:::{{ stacks.defaults.output.configbucket }}/{{ ENVIRONMENT }}/config/service/{{ serviceName }}.yml

  logs:
    - name: application

  service:
    healthCheckGracePeriod: 150

  scaling:
    cpuTargetTrackingScalingPolicyPercentage: 50
    memoryTargetTrackingScalingPolicyPercentage: 20

  datadog:
    apmEnabled: true
    logsEnabled: true

environments:
  - name: env-default
    datadog: false
    ecs:
      memory: 512
      cpu: 256

  - name: staging
    datadog: false
    ecs:
      memory: 1024
      cpu: 512
      maxCount: 2

  - name: production
    datadog: true
    ecs:
      memory: 2048
      cpu: 1024
      service:
        desiredCount: 4
        maxCount: 16
