---
serviceName: frontend
region: eu-west-1
exposure: public
dns: frontend
owner: squad-haricots

messages:
 publish:
 consume:

alarms:
  cpuAmber: 61
  cpuRed: 80
  elbLatencyAmber: 0.8
  elbLatencyRed: 1.2

logs:
  - name: pm2Log
    filters:
      - name: warningCount
        pattern: '[date, dash, status=\"warning:\", ...]'
        threshold: 50
      - name: errorCount
        pattern: '[date, dash, status=\"error:\", ...]'
        threshold: 7
      - name: criticalCount
        pattern: '[date, dash, status=\"critical:\", ...]'
        threshold: 1
      - name: unparseableCookieCount
        pattern: '[date, dash, status=\"error:\", exception=\"un-parsable cookie value*\"]'
        threshold: 1
  - name: apacheAccessLog
    filters:
      - name: failedNewSubscriptionDueToSystemIssue
        pattern: '[..., request=\"GET /contact HTTP/1.1\", status=200, a,b,from=\"https://www.gousto.co.uk/checkout\",d]'
        threshold: 2
  - name: apacheErrorLog
  - name: apiTimeLog
  - name: laravelLog
    filters:
      - name: warningCount
        pattern: '[date, status=local.WARNING*, ...]'
        threshold: 20
      - name: errorCount
        pattern: '[date, status=local.ERROR*, ...]'
        threshold: 15
      - name: criticalCount
        pattern: '[date, status=local.CRITICAL*, ...]'
        threshold: 2
      - name: csrfHeaderCount
        pattern: '[date, status=local.WARNING*, exception, exception_type=*CsrfHeaderException*, ...]'
        threshold: 15

scaling:
  type: cpu
  upAt: 60 # %
  upBy: 100 # %
  downAt: 30 # %
  downBy: 50 # %
  cooldown: 1200 # The amount of time, in seconds, after a scaling activity completes before any further trigger-related scaling activities can start.

healthCheck:
  target : 'HTTP:80/ping'
  healthyThreshold: 2
  unhealthyThreshold: 10
  interval: 5
  timeout: 4
  gracePeriod: 1080

environments:
  - name: staging
    instanceType: t2.micro
    minInstanceSize: 1
    maxInstanceSize: 2
    desiredInstanceSize: 1
    availability: businessHours

    deployment:
      style: immutable
      minInstancesInService: 1
      maxBatchSize: 1

  - name: env-default
    instanceType: t2.small
    minInstanceSize: 1
    maxInstanceSize: 1
    desiredInstanceSize: 1
    availability: businessHours

    deployment:
      style: inline

  - name: production
    instanceType: t2.medium
    minInstanceSize: 2
    maxInstanceSize: 8
    desiredInstanceSize: 2
    availability: alwaysOn

    deployment:
      style: immutable
      minInstancesInService: 2
      maxBatchSize: 1
