---
serviceName: webclient
region: eu-west-1
exposure: private
dns: webclient
owner: squad-radishes
rootVolumeSize: 16

alb:
  ec2:
    type: private
    rules:
      - priority: 94
        conditions:
          - field: host-header
            value: "[environment]-webclient.[cloudformation_output_domain]"

  ecs:
    - type: private
      rules:
        - priority: 91
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"
            - field: path-pattern
              value: "/box-prices"

    - type: private
      rules:
        - priority: 92
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"
            - field: path-pattern
              value: "/my-referrals"

    - type: private
      rules:
        - priority: 93
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"

messages:
 publish:
 consume:

alarms:
  cpuAmber: 61
  cpuRed: 80
  elbLatencyAmber: 0.8
  elbLatencyRed: 1.2

logs:
  - name: accessLogGroup
  - name: errorLogGroup
  - name: pm2Log
    filters:
      - name: errorCount
        pattern: '{$.log_level = \"error\"}'
        threshold: 7
      - name: criticalCount
        pattern: '{$.log_level = \"critical\"}'
        threshold: 1
      - name: unparseableCookieCount
        pattern: '{($.log_level = \"critical\") && ($.message =\"un-parsable cookie value*\")}'
        threshold: 1

  - name: apiTimeLog


scaling:
  type: cpu
  upAt: 60 # %
  upBy: 100 # %
  downAt: 30 # %
  downBy: 50 # %
  cooldown: 1200 # The amount of time, in seconds, after a scaling activity completes before any further trigger-related scaling activities can start.

healthCheck:
  target : 'HTTP:80/ping'
  healthyThreshold: 2
  unhealthyThreshold: 10
  interval: 5
  timeout: 4
  gracePeriod: 1080

environments:
  - name: staging
    instanceType: t2.small
    minInstanceSize: 0
    maxInstanceSize: 1
    desiredInstanceSize: 0
    ecsDesiredTaskCount: 2
    ecsMemory: 1024
    ecsCpu: 512

    deployment:
      style: immutable
      minInstancesInService: 0
      maxBatchSize: 1

  - name: env-default
    instanceType: t2.small
    minInstanceSize: 0
    maxInstanceSize: 0
    desiredInstanceSize: 0
    ecsDesiredTaskCount: 1
    ecsMemory: 512
    ecsCpu: 256

    deployment:
      style: inline

  - name: production
    instanceType: t2.medium
    minInstanceSize: 0
    maxInstanceSize: 8
    desiredInstanceSize: 0
    availability: alwaysOn
    ecsDesiredTaskCount: 12
    ecsMemory: 2048
    ecsCpu: 1024

    deployment:
      style: immutable
      minInstancesInService: 0
      maxBatchSize: 1
