---
serviceName: webclient
exposure: public
dns: webclient
owner: squad-radishes

ec2: false
ecs:
  alb:
    - type: public
      rules:
        - priority: 91
          conditions:
            - field: host-header
              value: "[environment]-webclient.[cloudformation_output_domain]"

  healthCheck:
    target : 'HTTP:80/ping'
    healthyThreshold: 2
    unhealthyThreshold: 10
    interval: 5
    timeout: 4

  containers:
    webclient:
      port: 80
      logName: application
      environment:
        ENVIRONMENT: '{{ ENVIRONMENT }}'

  taskRolePolicies:
    - effect: Allow
      actions:
        - s3:GetObject
        - s3:GetObjectVersion
      resources:
        - arn:aws:s3:::{{ stacks.defaults.output.configbucket }}/{{ ENVIRONMENT }}/config/service/{{ serviceName }}.yml

  logs:
    - name: application

  service:
    healthCheckGracePeriod: 150

  scaling:
    cpuTargetTrackingScalingPolicyPercentage: 50
    memoryTargetTrackingScalingPolicyPercentage: 20

environments:
  - name: staging
    ecs:
      memory: 1024
      cpu: 512
      maxCount: 2

  - name: env-default
    ecs:
      memory: 512
      cpu: 256

  - name: production
    ecs:
      memory: 2048
      cpu: 1024
      service:
        desiredCount: 4
        maxCount: 16
