apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
    - image: local/webclient-application
      context: .
      docker:
        dockerfile: images/webclient/Dockerfile
      sync:
        'src/**/*': .
    - image: local/webclient-webserver
      context: .
      docker:
        dockerfile: images/nginx/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - "k8s/k8s.yaml"
