apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: local/webclient-application
      context: .
      sync:
        manual:
          - src: dist/**/*
            dest: dist
            strip: dist/
          - src: node_modules/**/*
            dest: node_modules
            strip: node_modules/
          - src: src/config/**/*
            dest: config
            strip: src/config/
          - src: public/**/*
            dest: public
            strip: public/
          - src: process-docker.json
            dest: .
          - src: manifest.json
            dest: .
          - src: ecs_start.sh
            dest: .
      docker:
        dockerfile: images/webclient/Dockerfile
    - image: local/webclient-webserver
      context: .
      docker:
        dockerfile: images/nginx/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/dev/*.yaml
