apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
    - image: local/webclient-application
      context: .
      docker:
        dockerfile: images/webclient/Dockerfile
      sync:
        'src/dist/*': .
        'src/node_modules/*': .
        'src/config/*': .
        'src/manifest.json': .
        'src/process-docker.json': .
    - image: local/webclient-webserver
      context: .
      docker:
        dockerfile: images/nginx/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - "k8s/k8s.yaml"
