apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: local/webclient-application
      context: .
      sync:
        manual:
          - src: src/dist/**/*
            dest: dist
            strip: src/dist/
          - src: src/node_modules/**/*
            dest: node_modules
            strip: src/node_modules/
          - src: src/config/**/*
            dest: config
            strip: src/config/
          - src: src/public/**/*
            dest: public
            strip: src/public/
          - src: src/process-docker.json
            dest: .
            strip: src/
          - src: src/manifest.json
            dest: .
            strip: src/
          - src: src/ecs_start.sh
            dest: .
            strip: src/
      docker:
        dockerfile: images/webclient/Dockerfile
    - image: local/webclient-webserver
      context: .
      docker:
        dockerfile: images/nginx/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/dev/*.yaml
