---
version: 2.1
orbs:
  slack: circleci/slack@3.4.2

gousto_build_image: &gousto_build_image
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node10:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

gousto_build_image_docker: &gousto_build_image_docker
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node10builder:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

jobs:
  test-isomorphic-jest:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic jest tests
          command: cd src && npm run test:jest:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  publish-code-health:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup output folder
          command: mkdir /tmp/artifacts
      - run:
          name: Test coverage
          command: cd src && npm run test:jest:ci:coverage
      - run:
          name: eslint coverage
          command: cd src && scripts/run-eslint-ci.sh
      - run:
          name: Generate code health
          command: cd src && node ./scripts/print-code-health.js > /tmp/artifacts/${CODE_HEALTH_FILE_NAME}
      - store_artifacts:
          path: /tmp/artifacts

  setup-src:
    docker: *gousto_build_image
    steps:
      - checkout
      - run:
          name: Install global npm dependencies
          command: npm i -g gulp && npm i -g concurrently@2.2.0
      - run:
          name: Install isomorphic npm dependencies
          command: cd src && npm ci && npm run postinstall
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src
            - project/tests
            - project/regression
            - project/ansible
            - project/cloudformation
            - project/kubernetes
            - project/service.yml

  setup-platform:
    docker: *gousto_build_image_docker
    steps:
      - checkout
      - run:
          name: Setup platform
          command: /gousto/platform-setup.sh
      - setup_remote_docker
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --setup
          no_output_timeout: 10m
      - persist_to_workspace:
          root: ~/
          paths:
            - project/setup
            - project/scripts
            - project/ci_scripts
            - project/images
            - .circlerc

  build-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - run:
          name: Setup isomorphic
          command: source ~/.circlerc && setup/setup-isomorphic.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src

  build-nginx-image:
    docker: *gousto_build_image_docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --name nginx
          no_output_timeout: 10m

  build-webclient-image:
    docker: *gousto_build_image_docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Upload client to S3
          command: source ~/.circlerc && scripts/build-docker.sh
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --name webclient
          no_output_timeout: 20m

  test-e2e-selenium:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install curl
          command: apt-get -y update && apt-get -y install curl
      - run:
          name: Run e2e selenium tests
          command: source ~/.circlerc && scripts/validate.sh
      - slack/status:
          fail_only: true
          only_for_branches: 'develop'
          webhook: $E2E_TEST_NOTIFIER_WEBHOOK
          failure_message: 'The web E2E tests are failing on develop, please could a volunteer investigate. Playbook: https://gousto.atlassian.net/wiki/spaces/TECH/pages/1571914197/Debug+e2e+test+selenium+failure'


  test-e2e-selenium-mobile:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install curl
          command: apt-get -y update && apt-get -y install curl
      - run:
          name: Run e2e selenium tests mobile
          command: source ~/.circlerc && scripts/validate-mobile.sh
      - slack/status:
          fail_only: true
          only_for_branches: 'develop'
          webhook: $E2E_TEST_NOTIFIER_WEBHOOK
          failure_message: 'The mobile E2E tests are failing on develop, please could a volunteer investigate. Playbook: https://gousto.atlassian.net/wiki/spaces/TECH/pages/1571914197/Debug+e2e+test+selenium+failure'

  test-regression:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run regression tests
          command: source ~/.circlerc && scripts/validate-regression.sh
      - store_artifacts:
          path: ~/project/tests/regression/screenshots

  test-regression-mobile:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run regression tests mobile
          command: source ~/.circlerc && scripts/validate-regression-mobile.sh
      - store_artifacts:
          path: ~/project/tests/regression/screenshots

  deploy-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/deploy.sh

  deploy-containers:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy containers to ECS
          command: source ~/.circlerc && python ./ci_scripts/deploy_containers.py --service webclient
          no_output_timeout: 20m

  install-test-dependencies:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/install-test-dependencies.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/tests/regression/node_modules
            - project/tests/e2e/node_modules
            - .cache/Cypress


workflows:
  version: 2
  e2e:
    triggers:
      - schedule:
          cron: "0 9 * * 1-5"
          filters:
            branches:
              only:
                - develop
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
      - setup-platform:
          context: gousto-beta-aws-app-circleci
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - build-application
      - test-e2e-selenium-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - build-application
  e2e-manual:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - e2e-manual
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - e2e-manual
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - e2e-manual
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - e2e-manual
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - build-application
          filters:
            branches:
              only:
                - e2e-manual
      - test-e2e-selenium-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - build-application
          filters:
            branches:
              only:
                - e2e-manual

  lower-environment:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
      - build-nginx-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-platform
          filters:
            branches:
              only:
                - /^env-.*/
      - build-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - /^env-.*/
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - /^env-.*/
      - deploy-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - /^env-.*/
      - deploy-containers:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-nginx-image
            - build-webclient-image
          filters:
            branches:
              only:
                - /^env-.*/
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - /^env-.*/
      - test-regression:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - /^env-.*/
      - test-regression-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - /^env-.*/

  staging-environment:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - develop
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - develop
      - publish-code-health:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
          filters:
            branches:
              only:
                - develop
      - build-nginx-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-platform
          filters:
            branches:
              only:
                - develop
      - build-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - develop
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - develop
      - deploy-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
            - publish-code-health
          filters:
            branches:
              only:
                - develop
      - deploy-containers:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-nginx-image
            - build-webclient-image
            - publish-code-health
          filters:
            branches:
              only:
                - develop
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - develop
      - test-regression:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop
      - test-regression-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop

  production-environment:
    jobs:
      - setup-src:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - setup-platform:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - build-nginx-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-platform
          filters:
            branches:
              only:
                - master
      - build-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - master
      - build-webclient-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
      - deploy-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
      - deploy-containers:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-nginx-image
            - build-webclient-image
          filters:
            branches:
              only:
                - master
