---
version: 2
gousto_build_image: &gousto_build_image
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node10:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

jobs:
  install-dependencies:
    docker: *gousto_build_image
    steps:
      - checkout
      - run:
          name: Setup platform
          command: /gousto/platform-setup.sh
      - run:
          name: Install global yarn dependencies
          command: yarn global add gulp && yarn global add concurrently@2.2.0 && yarn global add bower
      - run:
          name: Setup Bower
          command: source ~/.circlerc && setup/setup-bower.sh
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - restore_cache:
          name: Restore isomorphic Yarn Package Cache
          keys:
            - yarn-packages-isomorphic-v2-{{ .Branch }}-{{ checksum "src/yarn.lock" }}
            - yarn-packages-isomorphic-v2-{{ .Branch }}
            - yarn-packages-isomorphic-v2-master
            - yarn-packages-isomorphic-v2-
      - run:
          name: Install isomorphic yarn dependencies
          command: cd src && yarn install

      - save_cache:
          name: Save isomorphic Yarn Package Cache
          key: yarn-packages-isomorphic-v2-{{ .Branch }}-{{ checksum "src/yarn.lock" }}
          paths:
            - src/node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  build-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - run:
          name: Setup isomorphic
          command: source ~/.circlerc && setup/setup-isomorphic.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  code-analysis:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Code analysis
          command: source ~/.circlerc && /bin/bash ./ci_scripts/code-analysis.sh

  test-isomorphic-mocha:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic mocha tests
          command: cd src && npm run test:mocha

  test-isomorphic-jest:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic jest tests
          command: cd src && yarn run test:jest:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  test-e2e-selenium:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run e2e selenium tests
          command: source ~/.circlerc && scripts/validate.sh

  deploy:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/deploy.sh

  build-image:
    docker: *gousto_build_image
    steps:
      - checkout
      - setup_remote_docker
      - run: /gousto/platform-setup.sh
      - run: 
          name: Create image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py
          no_output_timeout: 60m

workflows:
  version: 2
  pull-request-branch:
    jobs:
      - install-dependencies:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
      - test-isomorphic-mocha:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
      - test-isomorphic-jest:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
      - code-analysis:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master

  development-environment:
    jobs:
      - install-dependencies:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - test-isomorphic-mocha:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - test-isomorphic-jest:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - code-analysis:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-jest
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-mocha
            - test-isomorphic-jest
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - deploy:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
            - code-analysis
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy
          filters:
            branches:
              only:
                - develop
      - build-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-mocha
            - test-isomorphic-jest

      - build-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-mocha
            - test-isomorphic-jest


  production-environment:
    jobs:
      - install-dependencies:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - test-isomorphic-mocha:
          context: gousto-prod-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - test-isomorphic-jest:
          context: gousto-prod-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - test-isomorphic-mocha
            - test-isomorphic-jest
          filters:
            branches:
              only:
                - master
      - deploy:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
