---
version: 2.1

gousto_build_image: &gousto_build_image
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node12:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

gousto_platform_image: &gousto_platform_image
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/platformdeploy:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

jobs:
  test-isomorphic-jest:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic jest tests
          command: cd src && npm run test:jest:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  jest-coverage-report:
    docker: *gousto_build_image
    environment:
      TZ: "Europe/London"
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test coverage
          command: cd src && npm run test:jest:ci:coverage
          no_output_timeout: 30m
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src/coverage/coverage-summary.json

  eslint-generate-report:
    docker: *gousto_build_image
    environment:
      TZ: "Europe/London"
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: eslint report
          command: cd src && scripts/run-eslint-ci.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src/eslint-results.json

  publish-code-health:
    docker: *gousto_build_image
    environment:
      TZ: "Europe/London"
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup output folder
          command: mkdir /tmp/artifacts
      - run:
          name: Generate code health
          command: cd src && node ./scripts/print-code-health.js > /tmp/artifacts/${CODE_HEALTH_FILE_NAME}
      - store_artifacts:
          path: /tmp/artifacts

  setup-src:
    docker: *gousto_build_image
    steps:
      - checkout
      - run:
          name: Install global npm dependencies
          command: npm i -g gulp && npm i -g concurrently@2.2.0
      - run:
          name: Install isomorphic npm dependencies
          command: cd src && npm ci && npm run postinstall
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src
            - project/tests
            - project/regression
            - project/ansible
            - project/cloudformation
            - project/service.yml

  setup-platform:
    docker: *gousto_platform_image
    steps:
      - checkout
      - run:
          name: Setup platform
          command: /gousto/platform-setup.sh
      - setup_remote_docker
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --setup
          no_output_timeout: 10m
      - persist_to_workspace:
          root: ~/
          paths:
            - project/setup
            - project/scripts
            - project/ci_scripts
            - project/images
            - .circlerc

  setup-build-application:
    docker: *gousto_platform_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc
            - .npmrc

  build-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup isomorphic
          command: source ~/.circlerc && setup/setup-isomorphic.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src

  build-webclient-image:
    docker: *gousto_build_image
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Upload client to S3
          command: source ~/.circlerc && scripts/build-docker.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/setup
            - project/scripts
            - project/ci_scripts
            - project/images
            - .circlerc

  deploy-webclient-image:
    docker: *gousto_platform_image
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --name webclient
          no_output_timeout: 20m

  test-e2e-selenium:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install curl
          command: apt-get -y update && apt-get -y install curl
      - run:
          name: Run e2e selenium tests
          command: source ~/.circlerc && scripts/validate.sh

  test-regression:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run regression tests
          command: source ~/.circlerc && scripts/validate-regression.sh
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/mochawesome-bundle.html
          destination: report.html
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/app.js
          destination: assets/app.js
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/app.css
          destination: assets/app.css
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/MaterialIcons-Regular.woff
          destination: assets/MaterialIcons-Regular.woff

  test-regression-mobile:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run regression tests mobile
          command: source ~/.circlerc && scripts/validate-regression-mobile.sh
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/mochawesome-bundle.html
          destination: report.html
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/app.js
          destination: assets/app.js
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/app.css
          destination: assets/app.css
      - store_artifacts:
          path: ~/project/tests/regression/reports/html/assets/MaterialIcons-Regular.woff
          destination: assets/MaterialIcons-Regular.woff

  deploy-application:
    docker: *gousto_platform_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/deploy.sh

  deploy-containers:
    docker: *gousto_platform_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy containers to ECS
          command: source ~/.circlerc && python ./ci_scripts/deploy_containers.py --service webclient
          no_output_timeout: 20m

  install-test-dependencies:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/install-test-dependencies.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/tests/regression/node_modules
            - project/tests/e2e/node_modules
            - .cache/Cypress


workflows:
  version: 2

  e2e-manual:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - e2e-manual
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - e2e-manual
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - e2e-manual
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - e2e-manual
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - build-application
          filters:
            branches:
              only:
                - e2e-manual

  lower-environment:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
      - build-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - /^env-.*/
      - deploy-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-webclient-image
          filters:
            branches:
              only:
                - /^env-.*/
      - setup-build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - /^env-.*/
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-build-application
          filters:
            branches:
              only:
                - /^env-.*/
      - deploy-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - /^env-.*/
      - deploy-containers:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-webclient-image
          filters:
            branches:
              only:
                - /^env-.*/
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - /^env-.*/
      - test-regression:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - /^env-.*/
      - test-regression-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - /^env-.*/

  staging-environment:
    jobs:
      - setup-src:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - develop
      - setup-platform:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - develop
      - jest-coverage-report:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
      - eslint-generate-report:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
      - publish-code-health:
          context: gousto-beta-aws-app-circleci
          requires:
            - jest-coverage-report
            - eslint-generate-report
          filters:
            branches:
              only:
                - develop
      - build-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - develop
      - deploy-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-webclient-image
          filters:
            branches:
              only:
                - develop
      - setup-build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - develop
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-build-application
          filters:
            branches:
              only:
                - develop
      - deploy-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
            - publish-code-health
          filters:
            branches:
              only:
                - develop
      - deploy-containers:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-webclient-image
            - publish-code-health
          filters:
            branches:
              only:
                - develop
      - install-test-dependencies:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - develop
      - test-regression:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop
      - test-regression-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-test-dependencies
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop

  production-environment:
    jobs:
      - setup-src:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - setup-platform:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - setup-build-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-src
            - setup-platform
          filters:
            branches:
              only:
                - master
      - build-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-build-application
          filters:
            branches:
              only:
                - master
      - build-webclient-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
      - deploy-webclient-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-webclient-image
          filters:
            branches:
              only:
                - master
      - deploy-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
      - deploy-containers:
          context: gousto-prod-aws-app-circleci
          requires:
            - deploy-webclient-image
          filters:
            branches:
              only:
                - master
