---
version: 2
gousto_build_image: &gousto_build_image
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node10:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

gousto_build_image_docker: &gousto_build_image_docker
    - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${GOUSTO_ENVIRONMENT}/circleci-image/node10builder:latest
      aws_auth:
        aws_access_key_id: $AWS_ERC_ACCESS_KEY
        aws_secret_access_key: $AWS_ERC_SECRET_KEY

jobs:
  install-dependencies:
    docker: *gousto_build_image
    steps:
      - checkout
      - run:
          name: Setup platform
          command: /gousto/platform-setup.sh
      - run:
          name: Install global yarn dependencies
          command: yarn global add gulp && yarn global add concurrently@2.2.0
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - restore_cache:
          name: Restore isomorphic Yarn Package Cache
          keys:
            - yarn-packages-isomorphic-v2-{{ .Branch }}-{{ checksum "src/yarn.lock" }}
            - yarn-packages-isomorphic-v2-{{ .Branch }}
            - yarn-packages-isomorphic-v2-master
            - yarn-packages-isomorphic-v2-
      - run:
          name: Install isomorphic yarn dependencies
          command: cd src && yarn install

      - save_cache:
          name: Save isomorphic Yarn Package Cache
          key: yarn-packages-isomorphic-v2-{{ .Branch }}-{{ checksum "src/yarn.lock" }}
          paths:
            - src/node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  test-isomorphic-jest:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic jest tests
          command: cd src && yarn run test:jest:ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  test-isomorphic-jest-coverage:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run isomoprhic jest tests with coverage
          command: cd src && yarn run test:jest:ci:coverage
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src/coverage/

  compare-code-health:
    docker: *gousto_build_image_docker
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compare code health
          command: |
            cd src
            git diff --name-status origin/develop | node ./scripts/compare-code-health.js ${CODE_HEALTH_API_TOKEN} develop tmp/artifacts/${CODE_HEALTH_FILE_NAME}

  publish-code-health-artifact:
    docker: *gousto_build_image_docker
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish code health artifact
          command: |
            cd src
            mkdir /tmp/artifacts
            node ./scripts/print-code-health.js > /tmp/artifacts/${CODE_HEALTH_FILE_NAME}
      - store_artifacts:
          path: /tmp/artifacts

  setup-remote-image-repositories:
    docker: *gousto_build_image_docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --setup
          no_output_timeout: 10m

  build-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - run:
          name: Setup isomorphic
          command: source ~/.circlerc && setup/setup-isomorphic.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .circlerc

  build-nginx-image:
    docker: *gousto_build_image_docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --name nginx
          no_output_timeout: 10m

  build-webclient-image:
    docker: *gousto_build_image_docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Install global yarn dependencies
          command: yarn global add gulp && yarn global add concurrently@2.2.0
      - run:
          name: Setup common
          command: source ~/.circlerc && setup/setup-common.sh
      - run:
          name: Setup isomorphic
          command: source ~/.circlerc && setup/setup-isomorphic.sh
      - run:
          name: Upload client to S3
          command: source ~/.circlerc && scripts/build-docker.sh
      - run:
          name: Create & deploy image
          command: source ~/.circlerc && python ./ci_scripts/create_image.py --name webclient
          no_output_timeout: 20m

  eslint:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run eslint
          command: cd src && scripts/run-eslint-ci.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project/src/eslint-results.json

  code-analysis:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Code analysis
          command: source ~/.circlerc && /bin/bash ./ci_scripts/code-analysis.sh

  test-e2e-selenium:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run e2e selenium tests
          command: source ~/.circlerc && scripts/validate.sh

  test-e2e-selenium-mobile:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run e2e selenium tests mobile
          command: source ~/.circlerc && scripts/validate-mobile.sh

  test-e2e-cypress:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run e2e cypress tests
          command: source ~/.circlerc && scripts/validate-cypress.sh

  test-e2e-cypress-mobile:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run e2e cypress tests mobile
          command: source ~/.circlerc && scripts/validate-cypress-mobile.sh

  deploy-application:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run: source ~/.circlerc && scripts/deploy.sh

  deploy-containers:
    docker: *gousto_build_image
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy containers to ECS
          command: source ~/.circlerc && python ./ci_scripts/deploy_containers.py --service webclient
          no_output_timeout: 20m

workflows:
  version: 2
  pull-request-branch:
    jobs:
      - install-dependencies:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
      - test-isomorphic-jest-coverage:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
      - eslint:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - /^env-.*/
                - develop
                - master
#      - compare-code-health:
#          context: gousto-beta-aws-app-circleci
#          requires:
#            - test-isomorphic-jest-coverage
#            - eslint
#          filters:
#            branches:
#              ignore:
#                - /^env-.*/
#                - develop
#                - master

  development-environment:
    jobs:
      - install-dependencies:
          context: gousto-beta-aws-app-circleci
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - test-isomorphic-jest-coverage:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - setup-remote-image-repositories:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - build-nginx-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-remote-image-repositories
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - build-webclient-image:
          context: gousto-beta-aws-app-circleci
          requires:
            - setup-remote-image-repositories
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - eslint:
          context: gousto-beta-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - publish-code-health-artifact:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-jest-coverage
            - eslint
          filters:
            branches:
              only:
                - develop
      - code-analysis:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-jest-coverage
            - eslint
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - build-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - test-isomorphic-jest-coverage
            - eslint
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - deploy-application:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-application
            - code-analysis
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - deploy-containers:
          context: gousto-beta-aws-app-circleci
          requires:
            - build-nginx-image
            - build-webclient-image
            - code-analysis
          filters:
            branches:
              only:
                - /^env-.*/
                - develop
      - test-e2e-selenium:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop
      - test-e2e-selenium-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - develop
      - test-e2e-cypress:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - env-rockets
      - test-e2e-cypress-mobile:
          context: gousto-beta-aws-app-circleci
          requires:
            - deploy-application
            - deploy-containers
          filters:
            branches:
              only:
                - env-rockets



  production-environment:
    jobs:
      - install-dependencies:
          context: gousto-prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
      - test-isomorphic-jest:
          context: gousto-prod-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - setup-remote-image-repositories:
          context: gousto-prod-aws-app-circleci
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-nginx-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-remote-image-repositories
          filters:
            branches:
              only:
                - master
      - build-webclient-image:
          context: gousto-prod-aws-app-circleci
          requires:
            - setup-remote-image-repositories
          filters:
            branches:
              only:
                - master
      - build-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - test-isomorphic-jest
          filters:
            branches:
              only:
                - master
      - deploy-application:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-application
          filters:
            branches:
              only:
                - master
      - deploy-containers:
          context: gousto-prod-aws-app-circleci
          requires:
            - build-nginx-image
            - build-webclient-image
          filters:
            branches:
              only:
                - master
