export const loadingState = state => {
  const { PRODUCT_CATEGORIES_RECEIVE, PRODUCTS_STOCK_CHANGE, PRODUCTS_RECEIVE, USER_LOAD_REFERRAL_OFFER } = state.pending.toJS()

  return PRODUCT_CATEGORIES_RECEIVE || PRODUCTS_STOCK_CHANGE || PRODUCTS_RECEIVE || USER_LOAD_REFERRAL_OFFER !== false
}
