import { PropTypes } from 'prop-types'
import Immutable from 'immutable'

export const menuPropTypes = {
  basketNumPortionChange: PropTypes.func.isRequired,
  basketOrderLoaded: PropTypes.func.isRequired,
  basketRestorePreviousValues: PropTypes.func.isRequired,
  boxDetailsVisibilityChange: PropTypes.func.isRequired,
  cutOffDate: PropTypes.string.isRequired,
  disabled: PropTypes.bool.isRequired,
  isAuthenticated: PropTypes.bool.isRequired,
  menuLoadBoxPrices: PropTypes.func.isRequired,
  menuMobileGridViewSet: PropTypes.func.isRequired,
  orderCheckoutAction: PropTypes.func.isRequired,
  orderHasAnyProducts: PropTypes.func.isRequired,
  orderUpdateProducts: PropTypes.func.isRequired,
  productsLoadProducts: PropTypes.func.isRequired,
  productsLoadStock: PropTypes.func.isRequired,
  recipes: PropTypes.arrayOf(PropTypes.string).isRequired,
  slotId: PropTypes.string.isRequired,
  userOrders: PropTypes.instanceOf(Immutable.Map).isRequired,
  addressId: PropTypes.string,
  basketProducts: PropTypes.oneOfType([
    PropTypes.instanceOf(Immutable.Map),
    PropTypes.instanceOf(Immutable.Iterable),
  ]),
  boxSummaryDeliveryDays: PropTypes.instanceOf(Immutable.Map),
  boxSummaryDeliveryDaysLoad: PropTypes.func,
  boxSummaryShow: PropTypes.bool,
  deliveryDayId: PropTypes.string,
  detailVisibilityChange: PropTypes.func,
  filterRecipeGrouping: PropTypes.func,
  foodBrandDetails: PropTypes.shape({
    slug: PropTypes.string,
    name: PropTypes.string,
    borderColor: PropTypes.string,
  }),
  forceLoad: PropTypes.bool,
  hasRecommendations: PropTypes.bool,
  isLoading: PropTypes.bool,
  jfyTutorialFlag: PropTypes.bool,
  loginVisibilityChange: PropTypes.func,
  menuBrowseCTAShow: PropTypes.bool,
  menuBrowseCTAVisibilityChange: PropTypes.func,
  menuLoadDays: PropTypes.func,
  menuLoadingBoxPrices: PropTypes.bool,
  menuVariation: PropTypes.string,
  numPortions: PropTypes.number,
  orderId: PropTypes.string,
  params: PropTypes.object,
  portionSizeSelectedTracking: PropTypes.func,
  postcode: PropTypes.string,
  promoCode: PropTypes.string,
  query: PropTypes.object,
  recipeGroupingSelected: PropTypes.shape({
    slug: PropTypes.string,
    name: PropTypes.string,
    borderColor: PropTypes.string,
  }),
  shouldJfyTutorialBeVisible: PropTypes.func,
  storeOrderId: PropTypes.string,
  tariffId: PropTypes.number,
  triggerMenuLoad: PropTypes.func,
}

export const defaultMenuPropTypes = {
  isAuthenticated: false,
  disabled: false,
  forceLoad: false,
  isLoading: false,
  menuLoadingBoxPrices: false,
  numPortions: 2,
  orderCheckout: {
    orderId: '',
    url: ''
  },
  menuBrowseCTAVisibilityChange: () => { },
  menuMobileGridViewSet: () => { },
  basketRestorePreviousValues: () => { },
  shouldJfyTutorialBeVisible: () => { },
  portionSizeSelectedTracking: () => { },
  boxSummaryDeliveryDaysLoad: () => { },
  detailVisibilityChange: () => { },
  loginVisibilityChange: () => { },
  filterRecipeGrouping: () => { },
  triggerMenuLoad: () => { },
  menuLoadDays: () => { },
  basketProducts: Immutable.Map(),
  boxSummaryDeliveryDays: Immutable.Map(),
  addressId: '',
  promoCode: '',
  postcode: '',
  deliveryDayId: '',
  recipeGroupingSelected: null,
  query: {
    orderId: ''
  },
  storeOrderId: '',
  tariffId: null,
  params: {},
  boxSummaryShow: false,
  foodBrandDetails: null,
  hasRecommendations: false,
  jfyTutorialFlag: false,
  menuBrowseCTAShow: false,
  menuVariation: '',
  orderId: '',
}
