---

- name: install node
  shell: bash -lc "nvm install {{ node_version }}"
  register: output
  changed_when: "'already installed.' not in output.stderr"

- name: create alias directory
  file: path="{{ nvm_root }}/alias" state=directory

- name: set {{ node_version }} as default version
  copy: dest="{{ nvm_root }}/alias/default" content="{{ node_version }}"

- name: Install gulp
  command: npm i -g gulp

- name: npm cache clean
  command: npm cache clean
  args:
    chdir: "{{ directory }}"

- name: npm install
  command: npm ci && npm run postinstall
  args:
    chdir: "{{ directory }}"

- name: npm link
  command: npm link
  args:
    chdir: "{{ directory }}"

- name: npm run build nodeserver
  command: npm run build:dev
  args:
    chdir: "{{ directory }}"
