const actionTypes = {
  GET_HELP_APPLY_DELIVERY_COMPENSATION: 'GET_HELP_APPLY_DELIVERY_COMPENSATION',
  GET_HELP_CREATE_COMPLAINT: 'GET_HELP_CREATE_COMPLAINT',
  GET_HELP_LOAD_SHIPPING_ADDRESSES: 'GET_HELP_LOAD_SHIPPING_ADDRESSES',
  GET_HELP_LOAD_ORDERS: 'GET_HELP_LOAD_ORDERS',
  GET_HELP_LOAD_ORDER_AND_RECIPES_BY_IDS: 'GET_HELP_LOAD_ORDER_AND_RECIPES_BY_IDS',
  GET_HELP_LOAD_REFUND_AMOUNT: 'GET_HELP_LOAD_REFUND_AMOUNT',
  GET_HELP_LOAD_TRACKING_URL: 'GET_HELP_LOAD_TRACKING_URL',
  GET_HELP_STORE_ORDER: 'GET_HELP_STORE_ORDER',
  GET_HELP_VALIDATE_DELIVERY: 'GET_HELP_VALIDATE_DELIVERY',
  GET_HELP_HAS_SEEN_REPETITIVE_ISSUES: 'GET_HELP_HAS_SEEN_REPETITIVE_ISSUES'
}

export {
  actionTypes
}
