version: "3"
services:
  webclient:
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - ../:/usr/src/service
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
