version: "3"
services:
  webclient:
    image: webclient
    container_name: webclient
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - dps

networks:
  dps:
    external: true
