<?php

return [
    'main' => [
        'home' => [
            'title' => 'Food Boxes | Get Fresh Food &amp; Ingredients Delivered | Gousto',
            'description' => 'Choose recipes and get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Food Boxes | Get Fresh Food &amp; Ingredients Delivered | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Choose recipes, get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Food Boxes | Get Fresh Food &amp; Ingredients Delivered | Gousto',
            'twitter-description' => 'Choose recipes, get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',

        ],
        'box-prices' => [
            'title' => 'Recipe Box | Ingredients for Easy Recipes Delivered | Gousto',
            'description' => 'Discover our award-winning recipe boxes. Choose recipes and get fresh, pre-portioned ingredients delivered to your home with FREE delivery.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Recipe Box | Ingredients for Easy Recipes Delivered | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Discover our award-winning recipe boxes. Choose recipes and get fresh, pre-portioned ingredients delivered to your home with FREE delivery.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Recipe Box | Ingredients for Easy Recipes Delivered | Gousto',
            'twitter-description' => 'Discover our award-winning recipe boxes. Choose recipes and get fresh, pre-portioned ingredients delivered to your home with FREE delivery.',

        ],
        'cookbook' => [
            'title' => 'Recipes | Quick &amp; Easy Dinner Ideas from Gousto',
            'description' => 'Quick and easy recipes to cook at home. Explore our online cookbook of recipe ideas, with a wide range of tasty meals to choose from.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Recipes | Quick &amp; Easy Dinner Ideas from Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Quick and easy recipes to cook at home. Explore our online cookbook of recipe ideas, with a wide range of tasty meals to choose from.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Recipes | Quick &amp; Easy Dinner Ideas from Gousto',
            'twitter-description' => 'Quick and easy recipes to cook at home. Explore our online cookbook of recipe ideas, with a wide range of tasty meals to choose from.',

        ],
        'learn-more' => [
            'title' => 'Home Delivery Meal Kits: How Does Gousto Work?',
            'description' => 'Learn more about Gousto, and how to receive fresh, delicious recipes straight to your door.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Home Delivery Meal Kits: How Does Gousto Work?',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Learn more about Gousto, and how to receive fresh, delicious recipes straight to your door.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Home Delivery Meal Kits: How Does Gousto Work?',
            'twitter-description' => 'Learn more about Gousto, and how to receive fresh, delicious recipes straight to your door.',

        ],
        'we-care' => [
            'title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'twitter-description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',

        ],
        'contact' => [
            'title' => 'Contact Gousto: How to Get in Touch | Gousto',
            'description' => 'You can contact us by phone, email, or post! Find all our contact information at our website',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Contact Gousto: How to Get in Touch | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'You can contact us by phone, email, or post! Find all our contact information at our website',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Contact Gousto: How to Get in Touch | Gousto',
            'twitter-description' => 'You can contact us by phone, email, or post! Find all our contact information at our website',

        ],
        'refer' => [
            'title' => Request::segment(2) . 'recommends you try Gousto and save up to £' . Config::get('referral.whats_for_them') ,
            'description' => 'Sign up to Gousto using ' . Request::segment(2) . ' personal voucher code,' . Request::segment(3) . ', and save up to &pound;'. Config::get('referral.whats_for_them')  .' on your first Gousto Box.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => Request::segment(2) . 'recommends you try Gousto and save up to &pound;' . Config::get('referral.whats_for_them'),
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Sign up to Gousto using ' . Request::segment(2) . ' personal voucher code,' . Request::segment(3) . ', and save up to &pound;'. Config::get('referral.whats_for_them')  .' on your first Gousto Box.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => Request::segment(2) . 'recommends you try Gousto and save up to £pound;' . Config::get('referral.whats_for_them') ,
            'twitter-description' => 'Sign up to Gousto using ' . Request::segment(2) . ' personal voucher code,' . Request::segment(3) . ', and save up to &pound;'. Config::get('referral.whats_for_them')  .' on your first Gousto Box.',
        ],
        'terms-of-use' => [
            'title' => 'Website Terms of Use - Gousto',
            'description' => 'Read the terms of use for our website – including full terms and conditions and policies',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Website Terms of Use - Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Read the terms of use for our website – including full terms and conditions and policies',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Website Terms of Use - Gousto',
            'twitter-description' => 'Read the terms of use for our website – including full terms and conditions and policies',
        ],
        'terms-and-conditions' => [
            'title' => 'Terms &amp; Conditions for Sale of Goods - Gousto',
            'description' => 'Read the terms of use for our website – including full terms and conditions and policies',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Terms &amp; Conditions for Sale of Goods - Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Read the terms of use for our website – including full terms and conditions and policies',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Terms &amp; Conditions for Sale of Goods - Gousto',
            'twitter-description' => 'Read the terms of use for our website – including full terms and conditions and policies',
        ],
        'privacy-statement' => [
            'title' => 'Privacy Statement and Cookies Policy - Gousto',
            'description' => 'Read the Privacy Statement and Cookies Policy for Gousto',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Privacy Statement and Cookies Policy - Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Read the Privacy Statement and Cookies Policy for Gousto',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Privacy Statement and Cookies Policy - Gousto',
            'twitter-description' => 'Read the Privacy Statement and Cookies Policy for Gousto',
        ],

        'reset-password' => [
            'title' => 'Reset Your Password - Gousto',
            'description' => 'Reset your password for Gousto using our handy website form',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Reset Your Password - Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Reset your password for Gousto using our handy website form',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Reset Your Password - Gousto',
            'twitter-description' => 'Reset your password for Gousto using our handy website form',
        ],
    ],

    'signup' => [
        'title' => 'Sign Up for Gousto',
        'description' => 'Sign up for Gousto\'s award-winning recipe kits, with FREE delivery',
        'keywords' => 'healthy diet, balanced diet, healthy recipes',
        'og-title' => 'Sign Up for Gousto',
        'og-image' => image_path('images/photos/gousto-share-box.jpg'),
        'og-description' => 'Sign up for Gousto\'s award-winning recipe kits, with FREE delivery',
        'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
        'twitter-title' => 'Sign Up for Gousto',
        'twitter-description' => 'Sign up for Gousto\'s award-winning recipe kits, with FREE delivery',

    ],
    'values' => [
        'our-values' => [
            'title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'We Care: Our Approach to Food &amp; Ingredients | Gousto',
            'twitter-description' => 'We\'re incredibly passionate about our ingredients and want to supply you with the very best.',

        ],
        'meat-and-poultry' => [
            'title' => 'Higher Welfare British Meat & Poultry | Gousto',
            'description' => 'Great food starts with great ingredients, which is why we only source high quality meat and poultry, as well as award-winning free range eggs.',
            'keywords' => 'high quality meat, animal wellfare, british meat, free range eggs',
            'og-title' => 'Higher Welfare British Meat & Poultry | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Great food starts with great ingredients, which is why we only source high quality meat and poultry, as well as award-winning free range eggs.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Higher Welfare British Meat & Poultry | Gousto',
            'twitter-description' => 'Great food starts with great ingredients, which is why we only source high quality meat and poultry, as well as award-winning free range eggs.',

        ],
        'vegetables' => [
            'title' => 'Vegetable Sourcing - Gousto',
            'description' => 'Discover how Gousto sources delicious fruit and vegetables for our recipe kit boxes.',
            'keywords' => 'vegetables, vegetables, seasonal vegetables, veg',
            'og-title' => 'Vegetable Sourcing - Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Discover how Gousto sources delicious fruit and vegetables for our recipe kit boxes.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Vegetable Sourcing - Gousto',
            'twitter-description' => 'Discover how Gousto sources delicious fruit and vegetables for our recipe kit boxes.',

        ],
        'sustainable-food' => [
            'title' => 'Sustainable & Seasonal Food: Why Choose Gousto? | Gousto',
            'description' => 'We\'re committed to sustainable food - sourcing fresh, seasonal ingredients from our trusted local suppliers and farms.',
            'keywords' => 'sustainability, soil association, food miles',
            'og-title' => 'Sustainable & Seasonal Food: Why Choose Gousto? | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'We\'re committed to sustainable food - sourcing fresh, seasonal ingredients from our trusted local suppliers and farms.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Sustainable & Seasonal Food: Why Choose Gousto? | Gousto',
            'twitter-description' => 'We\'re committed to sustainable food - sourcing fresh, seasonal ingredients from our trusted local suppliers and farms.',

        ],
        'local-farming' => [
            'title' => 'Our Approach to Sourcing Local Food | Gousto',
            'description' => 'Were passionate about food provenance, and are dedicated to providing quality, local produce from trusted suppliers',
            'keywords' => 'local food, british food, locally sourced',
            'og-title' => 'Our Approach to Sourcing Local Food | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Were passionate about food provenance, and are dedicated to providing quality, local produce from trusted suppliers',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Our Approach to Sourcing Local Food | Gousto',
            'twitter-description' => 'Were passionate about food provenance, and are dedicated to providing quality, local produce from trusted suppliers',

        ],
        'suppliers' => [
            'title' => 'Food Traceability: Our Commitment to Food Provenance | Gousto',
            'description' => 'We\'re committed to traceability with the food and ingredients that we source. We only source produce from trusted local suppliers',
            'keywords' => 'food suppliers, sourcing produce, ingredients',
            'og-title' => 'Food Traceability: Our Commitment to Food Provenance | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'We\'re committed to traceability with the food and ingredients that we source. We only source produce from trusted local suppliers',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Food Traceability: Our Commitment to Food Provenance | Gousto',
            'twitter-description' => 'We\'re committed to traceability with the food and ingredients that we source. We only source produce from trusted local suppliers.',

        ],
        'reducing-food-waste' => [
            'title' => 'Reducing Food Waste: Our Mission to Stop Food Waste | Gousto',
            'description' => 'Stop food waste at home with Gousto\'s innovative recipe boxes. Get fresh, pre-portioned ingredients to cook at home - with zero waste.',
            'keywords' => 'reduce food waste, love food hate waste, meal plan',
            'og-title' => 'Reducing Food Waste: Our Mission to Stop Food Waste | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Stop food waste at home with Gousto\'s innovative recipe boxes. Get fresh, pre-portioned ingredients to cook at home - with zero waste.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Reducing Food Waste: Our Mission to Stop Food Waste | Gousto',
            'twitter-description' => 'Stop food waste at home with Gousto\'s innovative recipe boxes. Get fresh, pre-portioned ingredients to cook at home - with zero waste.',

        ],
        'healthy-food' => [
            'title' => 'Healthy Food Delivery: Wholesome &amp; Tasty Cooking | Gousto',
            'description' => 'Discover wholesome, tasty recipes with Gousto\'s healthy food box delivery. Choose from delicious recipes, delivered to you with FREE delivery.',
            'keywords' => 'healthy diet, balanced diet, healthy recipes',
            'og-title' => 'Healthy Food Delivery: Wholesome &amp; Tasty Cooking | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Discover wholesome, tasty recipes with Gousto\'s healthy food box delivery. Choose from delicious recipes, delivered to you with FREE delivery.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Healthy Food Delivery: Wholesome &amp; Tasty Cooking | Gousto',
            'twitter-description' => 'Discover wholesome, tasty recipes with Gousto\'s healthy food box delivery. Choose from delicious recipes, delivered to you with FREE delivery.',

        ],
    ],
    'account' => [
        'title' => 'My Gousto Account - Gousto',
        'description' => 'Choose recipes and get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',
        'keywords' => 'healthy diet, balanced diet, healthy recipes',
        'og-title' => 'My Gousto Account - Gousto',
        'og-image' => image_path('images/photos/gousto-share-box.jpg'),
        'og-description' => 'Choose recipes and get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',
        'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
        'twitter-title' => 'My Gousto Account - Gousto',
        'twitter-description' => 'Choose recipes and get fresh ingredients delivered to your door. Our award-winning food boxes include FREE delivery. Enjoy a new menu each week!',

    ],
    'errors' => [
        '404' => [
            'title' => 'Sorry – Page Not Found | Gousto',
            'description' => 'Sorry. The page you are looking for can\'t be found. Please try again or contact our customer care team.',
            'keywords' => 'Gousto, recipe delivery, ingredients, fresh, healthy food, cooking',
            'og-title' => 'Sorry – Page Not Found | Gousto',
            'og-image' => image_path('images/photos/gousto-share-box.jpg'),
            'og-description' => 'Sorry. The page you are looking for can\'t be found. Please try again or contact our customer care team.',
            'twitter-image' => image_path('images/photos/gousto-share-box.jpg'),
            'twitter-title' => 'Sorry – Page Not Found | Gousto',
            'twitter-description' => 'Sorry. The page you are looking for can\'t be found. Please try again or contact our customer care team.',

        ],
    ]
];
