const GOUSTO_RECAPTCHA_PRIVATE_KEY = '6LcjBd8UAAAAANgAZu3GJi1SlSZ5Yof9leBz-z5q'
const GOOGLE_RECAPTCHA_TEST_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

export const RECAPTCHA_PRIVATE_KEY = (
  __ENV__ === 'production'
  ? GOUSTO_RECAPTCHA_PRIVATE_KEY
  : GOOGLE_RECAPTCHA_TEST_PRIVATE_KEY
)
