name: PRs to master must be from develop
on:
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.ref == 'develop'
        run: exit 0
      - if: github.event.pull_request.head.ref != 'develop'
        run: exit 1
