name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'develop'

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout PR changes
      run: |
        # Fill out branch history to allow for differential builds
        # Un-shallow clone
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        # Get base branch history
        git fetch origin develop:develop --depth=100
        # Get topic branch history (and switch to it)
        git fetch origin ${{ github.event.pull_request.head.ref }} --depth=$(( ${{ github.event.pull_request.commits }} + 1 ))
        git checkout ${{ github.event.pull_request.head.ref }}
    - name: Get branch point
      id: branch_point
      run: |
        # Find common ancestor where topic branch diverged from base branch
        BRANCH=$( git rev-parse --abbrev-ref HEAD )
        BRANCH_POINT=$( git merge-base $BRANCH develop )
        # Bail out if not found
        [[ -z BRANCH_POINT ]] && echo "No branching point found; if develop has drifted by >100 commits then rebase the PR branch" && exit 1
        # Set var; use by reading "steps.branch_point.outputs.REF"
        echo "::set-output name=REF::$BRANCH_POINT"
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.x'
    - uses: pioug/la-cle@v1.0.0 # set up a git ssh key so npm can install our private git repo dependencies (gousto-gulp and gousto-lumberjack-js)
      with:
        GH_SSH_KEY: ${{ secrets.GH_SSH_KEY }}
    - name: Configure AWS credentials & auth with CA
      id: codeartifact_authenticate
      run: |
        aws configure set region eu-west-1
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain gousto --domain-owner 472493421475 --query authorizationToken --output text`
        echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
        echo "::set-output name=CODEARTIFACT_AUTH_TOKEN::$CODEARTIFACT_AUTH_TOKEN"
    - name: Set npm registry CA auth token
      run: |
        yarn config unset npmScopes &&
        yarn config set npmRegistryServer "https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/" &&
        yarn config set 'npmRegistries["https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/"].npmAuthToken' "${{ steps.codeartifact_authenticate.outputs.CODEARTIFACT_AUTH_TOKEN }}" &&
        yarn config set 'npmRegistries["https://gousto-472493421475.d.codeartifact.eu-west-1.amazonaws.com/npm/proxy-repository/"].npmAlwaysAuth' "true"
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
          src/apps/webclient/libs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/bower.json') }}-${{ hashFiles('.yarn/releases/yarn-*') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install --immutable
    - name: Debug differential build
      run: |
        # Print git state to confirm changes are as expected
        echo "Git branches:"
        git branch
        echo "Branch history:"
        git log --oneline --graph ${{ github.event.pull_request.head.ref }} develop
        echo "BRANCH_POINT value is: ${{ steps.branch_point.outputs.REF }}"
        echo "Changed files:"
        git diff --name-status ${{ steps.branch_point.outputs.REF }}
        echo "Webclient lint files:"
        yarn workspace-changes webclient --since=${{ steps.branch_point.outputs.REF }} --filter=lint
    - name: Lint (apps/webclient)
      working-directory: src/apps/webclient
      run: |
        # Optionally run eslint if required
        yarn workspace-changes webclient --since=${{ steps.branch_point.outputs.REF }} --filter=lint > lint-changes
        if [ -s lint-changes ]; then
          ./scripts/run-eslint-ci.sh $( cat lint-changes )
        fi
    - name: Lint (feature modules)
      run: yarn workspaces foreach --include '@features/*' --verbose run lint
    - name: Unit test (feature modules)
      run: yarn workspaces foreach --include '@features/*' --verbose run test:unit
    - name: Typecheck (feature modules)
      run: yarn workspaces foreach --include '@features/*' --verbose run typecheck
    - name: Lint (apps/webclient)
      run: ./scripts/run-eslint-ci.sh
      working-directory: src/apps/webclient
    - name: Typecheck tests
      run: yarn workspace webclient typecheck:tests
    - name: Unit test (apps/webclient)
      run: yarn workspace webclient test:jest:ci:coverage
    - name: Compare code health
      run: git diff --name-status ${{ steps.branch_point.outputs.REF }} | node ./scripts/compare-code-health.js develop tmp/artifacts/code_health.json
      working-directory: src/apps/webclient
      env:
       CIRCLECI_ACCESS_TOKEN: ${{ secrets.CIRCLECI_ACCESS_TOKEN }}
