name: "Danger JS"
on:
  pull_request:
    branches:
      - develop

jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Danger
      run: yarn dlx danger ci
      working-directory: ${{env.working-directory}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
