name: "Danger JS"
on:
  pull_request:
    branches:
      - develop

jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Danger JS Action
      uses: danger/danger-js@9.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DANGER_DISABLE_TRANSPILATION: true
