name: Create or update Production Deploy PR
on:
  push:
    branches:
      - "develop"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get open pull requests
        id: get_production_pr_number
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                pullRequests(baseRefName: "master", labels: ["production-deploy"], states: [OPEN], first: 1) {
                  nodes {
                    number,
                    bodyText
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse response to JSON
        id: pull_requests_json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.get_production_pr_number.outputs.data }}
          number: "repository.pullRequests.nodes[0].number"
          bodyText: "repository.pullRequests.nodes[0].bodyText"
      - name: Create Production PR if one doesn't exist
        if: ${{ !steps.pull_requests_json.outputs.number }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "master"
          branch: "develop"
          title: "Production Deploy"
          body: "- [ ] ${{ github.event.commits[0].message }} @${{ github.event.commits[0].author.username }}"
          labels: |
            "production-deploy"
      - name: Update Production PR if one exists
        if: ${{ steps.pull_requests_json.outputs.number }}
        uses: riskledger/update-pr-description@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "${{ steps.pull_requests_json.outputs.bodyText }}\n- [ ] ${{ github.event.commits[0].message }} @${{ github.event.commits[0].author.username }}"
