name: Pact tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'develop'

concurrency:
  group: pact-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '14.x'
    - uses: pioug/la-cle@v1.0.0 # set up a git ssh key so npm can install our private git repo dependencies (gousto-gulp and gousto-lumberjack-js)
      with:
        GH_SSH_KEY: ${{ secrets.GH_SSH_KEY }}
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
          **/src/libs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/bower.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: src
    - name: Run Gousto service adapter tests
      run: npm run test:gousto-adapters
      working-directory: src
    - name: Install emulation server dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: emulation-server
    - name: Start emulation server
      run: |
        npm start &
        ../scripts/waitForHttpPath.sh 3000 /_config/state 10
      working-directory: emulation-server
    - name: Verify emulation server satisfies Pact file expectations
      run: npm test
      working-directory: emulation-server
