name: Create or update Production Deploy PR

on:
  # Change to push to develop - get this as an input
  push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get open pull requests
        id: get_production_pr_number
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                pullRequests(baseRefName: "develop", first: 1) {
                  nodes {
                    title
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo results
        run: "echo 'PR number found: ${{ steps.get_production_pr_number.outputs.data }}'"
